name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: devenv

      - run: nix profile install nixpkgs#devenv

      - run: devenv shell -- composer install

      - run: devenv shell -- composer test

      - run: devenv shell -- composer analyze
